FROM node:8.9.4
MAINTAINER HTC-CS

RUN mkdir -p /tmp
ADD package.json /tmp/package.json
RUN cd /tmp && npm i --production --quiet --no-progress
RUN mkdir -p /src && cp -r /tmp/node_modules /src
WORKDIR /src
ADD . /src
RUN npm run build
RUN npm prune --production
